### ISSUE TITLE
Error on importing library in 0.0.3

### ISSUE THREAD

**Issue by plantysnake** [moi15moi/ass_tag_analyzer#6]
Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python\Python310\lib\site-packages\ass_tag_analyzer\__init__.py", line 1, in <module>
    from .ass_item import *
ModuleNotFoundError: No module named 'ass_tag_analyzer.ass_item'
```

Steps to reproduce:

1.  `pip install -U ass-tag-analyzer==0.0.3`
2. Run `import ass_tag_analyzer` in python

**Comment by moi15moi** [comment]
You were unlucky, I changed the build system today and I broke it.  I fixed the problem pretty quickly, but it looks like you had time to get the issue.

It has been resolved in 0.0.4
